name: CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build-and-test:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore
        run: dotnet restore symi.sln

      - name: Build Release
        run: dotnet build symi.sln --configuration Release --no-restore

      - name: Test (TRX)
        run: dotnet test Symi.Tests/Symi.Tests.csproj --configuration Release --no-build --logger "trx;LogFileName=test-results.trx" --results-directory ./TestResults

      - name: Publish Test Report
        if: always()
        uses: dorny/test-reporter@v1
        with:
          name: .NET Tests
          path: TestResults/**/*.trx
          reporter: dotnet-trx

      - name: Upload TRX Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-trx
          path: TestResults/**/*.trx